format = """
[î‚¶](#8AADF4)\
$os\
$username\
[î‚°](fg:#8AADF4 bg:#F5BDE6)\
$directory\
[î‚°](fg:#F5BDE6 bg:#B7BDF8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$bun\
$nim\
$rust\
$scala\
[î‚°](fg:#B7BDF8 bg:#0db7ed)\
$docker_context\
[î‚°](fg:#0db7ed bg:#f14e32)\
$git_branch\
$git_status\
[î‚°](fg:#f14e32 bg:#33658A)\
$time\
[î‚° ](fg:#33658A)\
"""

[username]
show_always = true
style_user = "bg:#8AADF4 fg:#212121"
style_root = "bg:#8AADF4 fg:#212121"
format = '[$user ]($style)'
disabled = false

[directory]
read_only = " ó°Œ¾"
style = "bg:#F5BDE6 fg:#212121"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "~/..î—¾../"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[aws]
symbol = "îŒ½  "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[buf]
symbol = "ï’ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = "î˜ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = "ï„Œ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[crystal]
symbol = "î˜¯ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = "î˜ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#0db7ed fg:#212121"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = "î˜­ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[fennel]
symbol = "îš¯ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[fossil_branch]
symbol = "ï˜ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜ "
style = "bg:#f14e32 fg:#212121"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f14e32 fg:#212121"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[guix_shell]
symbol = "ïŒ¥ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[haxe]
symbol = "î™¦ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[hg_branch]
symbol = "ï˜ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[hostname]
ssh_symbol = "î¬ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = "î˜´ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = "î˜  "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[memory_usage]
symbol = "ó°› "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[meson]
symbol = "ó°”· "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = "ïŒ“ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[bun]
symbol = "ğŸ”"
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[ocaml]
symbol = "î™º "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "ó°— "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[perl]
symbol = "î™¾ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = "î˜ˆ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[pijul_channel]
symbol = "ï˜ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "îˆµ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[rlang]
symbol = "ó°Ÿ” "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = "î‘ "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "ó±˜— "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = "î• "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = "îš© "
style = "bg:#B7BDF8 fg:#212121"
format = '[ $symbol ($version) ]($style)'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
# â™¥
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'
